openapi: 3.0.3
info:
  title: User Service API
  version: 1.0.0
  description: API для сервиса пользователей.

paths:
  /v1/createUser:
    post:
      summary: Регистрация нового пользователя
      description: Регистрация пользователя по логину, паролю и электронной почте.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
        '400':
          description: Ошибка валидации входящих данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/login:
    post:
      summary: Аутентификация пользователя
      description: Вход пользователя в систему по логину и паролю.
      requestBody:
         required: true
         content:
           application/json:
             schema:
                type: object
                properties:
                  login:
                    type: string
                  password:
                    type: string
                required:
                  - login
                  - password
      responses:
        '200':
          description: Успешная авторизация
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Неверный логин или пароль
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /v1/getProfile:
    get:
      summary: Получение данных профиля
      description: Получения профиля авторизованного пользователя.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Успешное получение данных профиля
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
        '401':
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Обновление профиля после аутентификации
      description: Изменение профиля пользователя после авторизации.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileUpdate'
      responses:
        '200':
          description: Профиль успешно обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
        '400':
          description: Ошибка в данных, присланных для обновления
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    UserRegistration:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
        email:
          type: string
          format: email
      required:
        - login
        - password
        - email

    UserProfileUpdate:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        birthDate:
          type: string
          format: date
        mail:
          type: string
          format: email
        phoneNumber:
          type: string
        additionalAttributes:
          type: object
          additionalProperties:
            type: string

    UserProfileResponse:
      type: object
      properties:
        login:
          type: string
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        birthDate:
          type: string
          format: date
        mail:
          type: string
          format: email
        phoneNumber:
          type: string
        additionalAttributes:
          type: object
          additionalProperties:
            type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
